[package]
name = "hook"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"

[dependencies.windows]
version = "0.61"
features = [
  "Win32_UI_WindowsAndMessaging",
  "Win32_Security",
  "Win32_System_Memory",
  "Win32_System_SystemServices",
]
